Footer header
ComicScrip/locab pull request #13
Opened 2022-06-03 13:27 UTC by dialloth

2022-06-06 08:24 UTC, ComicScrip commented
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/16140010/172124174-edc6e90a-ffb5-4950-b4c6-e75b05d7b9a3.png">

2022-06-06 08:37 UTC, ComicScrip requested changes

2022-06-06 08:37 UTC, ComicScrip commented on .eslintrc.json
> +        "endOfLine": "auto"
On a pas besoin de ça normalement

2022-06-06 08:37 UTC, ComicScrip commented on cypress/integration/footer.spec.js
> +  it("displays all links and Image", () => {
ici on ne teste que l'affichage sur la page contact puisque c'est la dernière visitée

2022-06-06 08:37 UTC, ComicScrip commented on pages/index.js
> +/* eslint-disable prettier/prettier */
Ah non, il faut régler les soucis, pas juste désactiver les règles

2022-06-06 08:37 UTC, ComicScrip commented on styles/headerfooter/navbar.module.css
> +  /* display: flex;
code mort ?

2022-06-08 22:04 UTC, dialloth commented on .eslintrc.json
> +        "endOfLine": "auto"
C'est ça qui m'a permis de régler certaines erreurs avec mes eslint

2022-06-08 22:06 UTC, dialloth commented on cypress/integration/footer.spec.js
> +  it("displays all links and Image", () => {
Ok

2022-06-09 14:50 UTC, Sim-guy reviewed
Menu burger à terminer + problème sur le placement des éléments du footer

2022-06-14 13:29 UTC, Sim-guy approved these changes

2022-06-14 14:35 UTC, NycoChavanoud requested changes
Manque de nettoyage et attentions, on ne desactive pas ESLINT ET PRETTIER pour regler les erreurs.. c'est pas une bonne solution

2022-06-14 14:35 UTC, NycoChavanoud commented on components/header.js
> +          {/* <li className={`${styles.navbar_item} ${styles.slideInDown-1}`}> */}
code mort! rien à faire en prod

2022-06-14 14:35 UTC, NycoChavanoud commented on components/iconsDesktop/index.js
> +/* eslint-disable prettier/prettier */
pourquoi  mettre en place des outils de contrôle si c'est pour les désactiver dans toutes les pages???

2022-06-14 14:35 UTC, NycoChavanoud commented on components/iconsDesktop/index.js
> +            // placeholder=" &#xf017;  <i class="fa-thin fa-clock"></i> Départ   <i class="fa-thin fa-location-dot"></i>"
toujours code mort

2022-06-14 14:35 UTC, NycoChavanoud commented on pages/index.js
> +/* eslint-disable prettier/prettier */
IDEM

2022-06-14 14:35 UTC, NycoChavanoud commented on pages/reservation/index.js
> +    if (newQuantity === "") {
if (!newQuantity) ... à essayer!

2022-06-14 14:35 UTC, NycoChavanoud commented on styles/globals.css
> +img {
attention à cette règle, va s'appliquer à toute les images. Eviter, sauf si cela est vraiment voulu, de mettre des règles de la sorte qui vont influé sur toutes les images furtures...

2022-06-15 13:17 UTC, merged