Back client
ComicScrip/locab pull request #48
Opened 2022-07-12 13:33 UTC by QuintinJouanne

2022-07-12 14:25 UTC, Claiirou approved these changes

2022-07-12 14:32 UTC, QuintinJouanne commented on components/backoffice/SearchCustomers.js
> +                  backCustomer.firstname
Je sais mais quand je l'enleve, le filter deconne grave

2022-07-12 14:45 UTC, Claiirou approved these changes

2022-07-12 15:07 UTC, ComicScrip requested changes

2022-07-12 15:07 UTC, ComicScrip commented on components/backoffice/SearchCustomers.js
> +                .filter((backCustomer) =>
plus besoin de filtrer ici puisqu'on le fait coté back

2022-07-12 15:07 UTC, ComicScrip commented on cypress/integration/customerAdmin.spec.js
> +  it("can create a new customer", () => {
et la modification ?

2022-07-13 07:03 UTC, QuintinJouanne commented on components/backoffice/dataBackCustomers.js
> +const dataBackCustomers = {
supprimé

2022-07-13 07:05 UTC, QuintinJouanne commented on components/backoffice/SearchCustomers.js
> +                .filter((backCustomer) =>
filter supprimé

2022-07-13 07:55 UTC, QuintinJouanne commented on cypress/integration/customerAdmin.spec.js
> +  it("can create a new customer", () => {
fait

2022-07-13 12:52 UTC, merged